packages:
  - examples/*

catalog:
  "@tailwindcss/vite": ^4.1.13
  "@types/react": 19.1.0
  "@types/react-dom": 19.1.0
  "@vitejs/plugin-react": ^4.5.1
  "@vitejs/plugin-react-swc": ^3.10.1
  clsx: ^2.1.1
  jazz-tools: ^0.18.13
  lucide-react: ^0.544.0
  react: 19.1.0
  react-dom: 19.1.0
  tailwindcss: ^4.1.13
  typescript: ^5.6.2
  vite: 6.3.5

ignoredBuiltDependencies:
  - "@swc/core"

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
  - react-native-nitro-modules
